### ISSUE TITLE
Path autogeneration fails when forge is used in multiple places

### ISSUE THREAD

**Issue by msporny** [digitalbazaar/bedrock-requirejs#2]
If a top-level project includes forge in its bower.json dependencies list and another package (like did-io) is also listed as a dependency that pulls in forge in its bower.json file, then the forge path that is generated results in a require.js script error.

Here's the forge path that is generated in the requirejs/main.js file:

```
"forge": "/bower-components/forge/js"
```

and the browser tries to load this path from the server:

```
/bower-components/forge/js.js
```

instead of just trying to specify the path, which is the proper thing to do. Appending '.js' to the path is incorrect in the case of forge.

**Comment by dlongley** [comment]
This has been fixed by removing custom `path` configuration in bedrock-views and adding `moduleType` (set to `amd`) in forge.
